include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		GLS

SOURCES = 		gls_interface.cc

PUBLIC_INCLUDES = 	gls_messages.h gls_interface.h
PUBLIC_LIBRARIES = 	libgls_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libgls_interface.a

# rules

libgls_interface.a:	gls_interface.o

include ../../Makefile.rules
