include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += -lgrid $(GLOBAL_LIBS)

MODULE_NAME = GRID

SOURCES = test_grid.c

PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = 

TARGETS = test_grid

# rules

test_grid:	test_grid.o

include ../../Makefile.rules
