include ../../Makefile.conf

# delete any fields you don't need

CFLAGS +=
IFLAGS += 
LFLAGS += $(INTERFACE_LIBS) $(GLOBAL_LIBS)
LINK = g++

MODULE_NAME = 		CAMERA

SOURCES = 		fake_camera.cpp

PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = 

TARGETS = 		fake_camera

fake_camera:		fake_camera.o

include ../../Makefile.rules
