include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		RADAR

SOURCES = 		radar_interface.cc

PUBLIC_INCLUDES = 	radar_messages.h radar_interface.h
PUBLIC_LIBRARIES = 	libradar_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libradar_interface.a

# rules

libradar_interface.a:	radar_interface.o

include ../../Makefile.rules
