include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		LDLRS

SOURCES = 		ldlrs_interface.cc

PUBLIC_INCLUDES = 	ldlrs_messages.h ldlrs_interface.h
PUBLIC_LIBRARIES = 	libldlrs_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libldlrs_interface.a

# rules

libldlrs_interface.a:	ldlrs_interface.o

include ../../Makefile.rules
