include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		ESTOP

SOURCES = 		estop_interface.cc

PUBLIC_INCLUDES = 	estop_messages.h estop_interface.h
PUBLIC_LIBRARIES = 	libestop_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libestop_interface.a

# rules

libestop_interface.a:	estop_interface.o

include ../../Makefile.rules
