include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		POWER

SOURCES = 		power_interface.cc

PUBLIC_INCLUDES = 	power_messages.h power_interface.h
PUBLIC_LIBRARIES = 	libpower_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libpower_interface.a

# rules

libpower_interface.a:	power_interface.o

include ../../Makefile.rules
