include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		SIMULATOR

SOURCES = 		simulator_interface.cc

PUBLIC_INCLUDES = 	simulator_interface.h simulator_messages.h
PUBLIC_LIBRARIES = 	libsimulator_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libsimulator_interface.a

# rules

libsimulator_interface.a:	simulator_interface.o

include ../../Makefile.rules
