include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		TIMESYNC

SOURCES = 		timesync_interface.cc

PUBLIC_INCLUDES = 	timesync_messages.h timesync_interface.h
PUBLIC_LIBRARIES = 	libtimesync_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libtimesync_interface.a


libtimesync_interface.a:	timesync_interface.o


include ../../Makefile.rules
