include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += -lhealthmon_interface -lparam_interface $(GLOBAL_LIBS)

MODULE_NAME = HEALTHMON

SOURCES = healthmon_test.c

PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = 

TARGETS = healthmon_test

# rules

healthmon_test:		healthmon_test.o

include ../../Makefile.rules
