#ifndef DGC_PASSAT_FSM_STATES_H
#define DGC_PASSAT_FSM_STATES_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  INITIALIZING_WAIT_FOR_DATA,
  
  PAUSEFOR_STOP_VEHICLE,
  PAUSEFOR_PRESHIFT_WAIT,
  PAUSEFOR_SHIFT_TO_PARK,
  PAUSEFOR_WAIT_WITH_BRAKE,
  PAUSEFOR_ENABLE_PARKING_BRAKE,
  PAUSEFOR_WAIT,
  PAUSEFOR_ENABLE_BRAKE,
  PAUSEFOR_DISABLE_PARKING_BRAKE,
  PAUSEFOR_SHIFT_TO_DRIVE,
  PAUSEFOR_WAIT_5SEC,

  PAUSEREV_STOP_VEHICLE,
  PAUSEREV_PRESHIFT_WAIT,
  PAUSEREV_SHIFT_TO_PARK,
  PAUSEREV_WAIT_WITH_BRAKE,
  PAUSEREV_ENABLE_PARKING_BRAKE,
  PAUSEREV_WAIT,
  PAUSEREV_ENABLE_BRAKE,
  PAUSEREV_DISABLE_PARKING_BRAKE,
  PAUSEREV_SHIFT_TO_REVERSE,
  PAUSEREV_WAIT_5SEC,
  
  FORWARD_STOP_VEHICLE,
  FORWARD_PRESHIFT_WAIT,
  FORWARD_SHIFT_TO_DRIVE,
  FORWARD_GO,

  REVERSE_STOP_VEHICLE,
  REVERSE_PRESHIFT_WAIT,
  REVERSE_SHIFT_TO_REVERSE,
  REVERSE_GO,

  FINISH_STOP_VEHICLE,
  FINISH_PRESHIFT_WAIT,
  FINISH_SHIFT_TO_PARK,
  FINISH_WAIT
} dgc_passat_fsm_state_t;

#ifdef __cplusplus
}
#endif

#endif
