include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		PLANNER

SOURCES = 		planner_interface.cc

PUBLIC_INCLUDES = 	planner_messages.h planner_interface.h
PUBLIC_LIBRARIES = 	libplanner_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libplanner_interface.a

# rules

libplanner_interface.a:		planner_interface.o

include ../../Makefile.rules
