include ../../Makefile.conf

IFLAGS += 

LFLAGS += -lipc_interface            

LINK = g++

MODULE_NAME = SYSTEM_TEST

SOURCES =  
	  
PUBLIC_INCLUDES = system_test.h
PUBLIC_LIBRARIES =  
PUBLIC_BINARIES = 

TARGETS = 
TEST_TARGETS = 
EVAL_TARGETS = 

# rules
                        
include ../../Makefile.rules
