include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		LATENCY

SOURCES = 		latency_interface.cc

PUBLIC_INCLUDES = 	latency_interface.h latency_messages.h
PUBLIC_LIBRARIES = 	liblatency_interface.a
PUBLIC_BINARIES = 

TARGETS = 		liblatency_interface.a

# rules

liblatency_interface.a:		latency_interface.o

include ../../Makefile.rules
