include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += -lb64 $(GLOBAL_LIBS)

MODULE_NAME = B64

SOURCES = b64_test.c

PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES = 
PUBLIC_BINARIES = 

TARGETS = b64_test

# rules

b64_test:	b64_test.o 

include ../../Makefile.rules
