include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		ERROR

SOURCES = 		error_interface.cc

PUBLIC_INCLUDES = 	error_messages.h error_interface.h
PUBLIC_LIBRARIES = 	liberror_interface.a
PUBLIC_BINARIES = 

TARGETS = 		liberror_interface.a

# rules

liberror_interface.a:	error_interface.o

include ../../Makefile.rules
