include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		GHOSTCAR

SOURCES = 		ghostcar_interface.cc

PUBLIC_INCLUDES = 	ghostcar_interface.h ghostcar_messages.h
PUBLIC_LIBRARIES = 	libghostcar_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libghostcar_interface.a

# rules

libghostcar_interface.a:	ghostcar_interface.o

include ../../Makefile.rules
