include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		APPLANIX

SOURCES = 		applanix_interface.cc

PUBLIC_INCLUDES = 	applanix_interface.h applanix_messages.h
PUBLIC_LIBRARIES = 	libapplanix_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libapplanix_interface.a

# rules

libapplanix_interface.a:	applanix_interface.o

include ../../Makefile.rules
