include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		LASER

SOURCES = 		laser_interface.cc

PUBLIC_INCLUDES = 	laser_interface.h laser_messages.h
PUBLIC_LIBRARIES = 	liblaser_interface.a
PUBLIC_BINARIES = 

TARGETS = 		liblaser_interface.a 

# rules

liblaser_interface.a:	laser_interface.o

include ../../Makefile.rules
