include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		IBEO

SOURCES = 		ibeo_interface.cc

PUBLIC_INCLUDES = 	ibeo_messages.h ibeo_interface.h
PUBLIC_LIBRARIES = 	libibeo_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libibeo_interface.a

# rules

libibeo_interface.a:	ibeo_interface.o

include ../../Makefile.rules
