include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		LOCALIZE

SOURCES = 		localize_interface.cc

PUBLIC_INCLUDES = 	localize_interface.h localize_messages.h
PUBLIC_LIBRARIES = 	liblocalize_interface.a
PUBLIC_BINARIES = 

TARGETS = 		liblocalize_interface.a

# rules

liblocalize_interface.a:	localize_interface.o

include ../../Makefile.rules
