include ../../Makefile.conf

CFLAGS +=
IFLAGS += 
LFLAGS += 

MODULE_NAME = 		PLAYBACK

SOURCES = 		playback_interface.cc

PUBLIC_INCLUDES = 	playback_interface.h playback_messages.h
PUBLIC_LIBRARIES = 	libplayback_interface.a
PUBLIC_BINARIES = 

TARGETS = 		libplayback_interface.a

# rules

libplayback_interface.a:	playback_interface.o

include ../../Makefile.rules
